### ISSUE TITLE
Mod just crashes when workshop table is right clicked [V1.21 - MC 1.10.2]

### ISSUE THREAD

**Issue by Cakx** [EngineersMods/EngineersWorkshop#26] opened 2017-04-11 23:24 UTC
###### **Forge Version & Engineer's Workshop Version**

Tried these two Forge Versions:

• Forge 12.18.3.2254
• Forge 12.18.3.2281

**• EngineersWorkshop-1.2.1-1.10.2.jar**

###### **Expected behavior**
I wanted to right click on the workshop table to open its UI.  (In single player creative mode)

###### **Actual Behavior**
Minecraft crashes when i click the workshop table. Every time.

###### **Link to Crashlog or Forgelog** *[If Applicable]*
[Crashlog-EW.txt](https://github.com/EngineersMods/EngineersWorkshop/files/914875/Crashlog-EW.txt)

###### **Steps to reproduce** *[If Applicable]*

I use MultiMC 5 for my Minecraft instances and mod testing.
The only Mod installed: 

jei_1.10.2-3.14.7.416

**It does NOT happen with this Version:
EngineersWorkshop-1.2.0-1.10.2.jar**

Here everything seems to be fine.

**Comment by DanNetwalker** [comment] 2017-04-19 23:03
Same problem. https://pastebin.com/2c2fa6xy

**Comment by JorVaCoding** [comment] 2017-04-29 20:28
I was not able to reproduce this, but it should be fixed now, just added a check to see if the list contains an index before actually getting it. 

 will be a version later today along with other bug fixes. (I'll once it's committed)

**Comment by JorVaCoding** [comment] 2017-04-29 22:06
1.3.0-1.10.2

**Closed as completed by JorVaCoding** 2017-04-29 22:06 UTC
Labels: bug, crash, fixed
