### ISSUE TITLE
Multiple Block Breaking Issues

### ISSUE THREAD

**Issue by medtryx** [EngineersMods/EngineersWorkshop#4] opened 2016-12-12 05:40 UTC
###### **Forge Version & Engineer's Workshop Version**
> forge-12.18.3.2185
    EngineersWorkshop-1.0.2-1.10.2.jar

###### **Expected behavior**
> Workshop Table should not instantly break, or drop when broken in creative mode. 

###### **Actual Behavior**
> In survival mode Workshop Table will break instantly if hit.  In Creative it will also drop the block when broke as well as it's contents.  The dropped item also tends to fly away when broken in both game modes.

**Comment by EwyBoy** [comment] 2016-12-12 19:41
Thank you for your bug report.
The issue is now fixed and will be included in the next patch. v1.0.3-1.10.2

**Closed as completed by EwyBoy** 2016-12-12 19:41 UTC
Labels: bug, known, fixed
