### ISSUE TITLE
Making 2 material alloys crash the server

### ISSUE THREAD

**Issue by misterfixit** [EngineersMods/EngineersWorkshop#27] opened 2017-04-25 19:43 UTC
###### **Forge Version & Engineer's Workshop Version**
> 12.18.3.2281 1.2.1-1.10.2

###### **Expected behavior**
> When using the alloy smelter in the workshop 2 item alloys such as electrum and vibrant alloy
instead of making the alloy it crashes the server

###### **Actual Behavior**
> It crashes the server

###### **Link to Crashlog or Forgelog** *[If Applicable]*
> https://gist.github.com/misterfixit/e2d1fc376d42298c7ee63fc3c3bafbe6

###### **Steps to reproduce** *[If Applicable]*
> Insert materials for any 2 alloy item

**Comment by JorVaCoding** [comment] 2017-04-29 20:36
The issue isn't because it's only two items, it's becuase its two items but the second/first slot isn't used (slots 1/3, 2/3)... 

 will be a version later today along with other bug fixes. (I'll once it's committed)

**Comment by JorVaCoding** [comment] 2017-04-29 22:05
1.3.0-1.10.2

**Closed as completed by JorVaCoding** 2017-04-29 22:05 UTC
Labels: bug, crash, mod compat, fixed
