### ISSUE TITLE
Divide by zero crash

### ISSUE THREAD

**Issue by VT-14** [EngineersMods/EngineersWorkshop#15] opened 2017-01-18 20:41 UTC
###### **Forge Version & Engineer's Workshop Version**
> Forge: 12.18.3.2221
Engineer's Workshop: 1.1.4-1.10.2
Minecraft 1.10.2
Personal modpack

###### **Expected behavior**
> No crash

###### **Actual Behavior**
> Game crashes after opening the Workshop GUI for a few seconds.  This only started happening after using the workshop for a few hours.  The workshop has 4 furnaces.  Some (but not all) crashes also had 3 power buffer upgrades installed.  I had also put Extra Utilities 2's Red Coal in the workshop, but removed that from both the workshop and my entire inventory, and still crashed.  Attempting to break and replace the table (in the same position, I have yet to try moving it) still crashes.

###### **Link to Crashlog or Forgelog** *[If Applicable]*
> Crash: https://gist.github.com/VT-14/c0547b3dcc5302c374e087dbe6a31af1
FML: https://gist.github.com/VT-14/087c1f7ac9391c47c02370f2d0ec29cd

###### **Steps to reproduce** *[If Applicable]*
> Not sure.  The bench in my single player world appears to crash consistently, but I haven't been able to reproduce the issue from scratch and determine a sequence to cause this crash.

**Comment by MiniKiwiNZ** [comment] 2017-02-02 06:24
Also experiencing this.
**Forge Version & Engineer's Workshop Version**
> Forge: 12.18.3.2215
> Engineer's Workshop: 1.1.4-1.10.2
> Minecraft: 1.10.2
> FTB Presents Skyfactory 3

**Unexpected Behavior**
> As above - Game crashes a few seconds after opening the workshop GUI. I have only placed the workshop down and opened it. Game remains responsive for several seconds and then closes. The server continues to run, and no other clients are disconnected.

**Crash Logs**
> Crash report from FML log: http://pastebin.com/w11fiWAt
> Minecraft crash report is the same

**Comment by heidrifx** [comment] 2017-02-05 22:26
Also experiencing this.
Forge Version & Engineer's Workshop Version

Forge: 12.18.3.2221
Engineer's Workshop: 1.1.4-1.10.2
Minecraft: 1.10.2
Custom Modpack

Unexpected Behavior

Like the first reports
As above - Game crashes a few seconds after opening the workshop GUI. Workshop uses two crafting tables and two furnaces and was powered by Actually Additions Tiny Coal. Made a change in the config to set the maximum power to 16k. Worked as intended but lately started crashing with "Divided by 0"

Crash Logs

Crash report from FML log: http://pastebin.com/sRbBZh7b
Minecraft crash report is the same

**Comment by JorVaCoding** [comment] 2017-03-10 23:39
I haven't been able to reproduce this in any environment, I added a fail-safe so it won't crash. It has to do with table capacity being 0. Closing issue unless something else comes up with this.

**Closed as completed** 2017-03-11 00:06 UTC
Labels: bug, crash, URGENT
